import type { Metadata } from "next";
import "./globals.css";
import Header from '@/components/header'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-red-200 w-full h-full">
      <Header></Header>
      {children}
      </body>
    </html>
  );
}
